export const images = [
  {
    author: 'Pavel Fedotov',
    name: "The Major's Marriage Proposal",
    year: '1852',
    imageNum: '0',
    category: 'realism',
  },
  {
    author: 'Edgar Degas',
    name: 'Blue Dancers',
    year: '1897',
    imageNum: '1',
    category: 'impressionism',
  },
  {
    author: 'Veronese',
    name: 'The Feast in the House of Levi',
    year: '1563',
    imageNum: '2',
    category: 'religion',
  },
  {
    author: 'Ilya Repin',
    name: 'Ivan the Terrible and His Son Ivan',
    year: '1885',
    imageNum: '3',
    category: 'realism',
  },
  {
    author: 'Konstantin Makovsky',
    name: 'Portrait of Tsarevna Sofia',
    year: '1890',
    imageNum: '4',
    category: 'portrait',
  },
  {
    author: 'Vasily Perov',
    name: 'Arrival of a New Governess in a Merchant House',
    year: '1866',
    imageNum: '5',
    category: 'realism',
  },
  {
    author: 'Michelangelo',
    name: 'The Creation of Adam',
    year: '1511',
    imageNum: '6',
    category: 'renaissance',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Horsemen',
    year: '1873',
    imageNum: '7',
    category: 'impressionism',
  },
  {
    author: 'Jan Vermeer',
    name: 'Mistress and Maid',
    year: '1667',
    imageNum: '8',
    category: 'painting',
  },
  {
    author: 'Vasily Polenov',
    name: 'Moscow Courtyard',
    year: '1877',
    imageNum: '9',
    category: 'landscape',
  },
  {
    author: 'Fyodor Vasilyev',
    name: 'Wet meadow',
    year: '1872',
    imageNum: '10',
    category: 'landscape',
  },
  {
    author: 'Ilya Repin',
    name: 'Send off of recruit',
    year: '1879',
    imageNum: '11',
    category: 'painting',
  },
  {
    author: 'Veronese',
    name: 'Venus and Mars',
    year: '1560',
    imageNum: '12',
    category: 'renaissance',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Alenushka',
    year: '1881',
    imageNum: '13',
    category: 'painting',
  },
  {
    author: 'Claude Lorrain',
    name: 'Seaport with the Embarkation of Saint Ursula',
    year: '1614',
    imageNum: '14',
    category: 'marine',
  },
  {
    author: 'Ilya Repin',
    name: 'Vechornytsi',
    year: '1881',
    imageNum: '15',
    category: 'painting',
  },
  {
    author: 'Jean-Honoré Fragonard',
    name: 'The Swing',
    year: '1767',
    imageNum: '16',
    category: 'renaissance',
  },
  {
    author: 'Arkhip Kuindzhi',
    name: 'A Birch Grove',
    year: '1879',
    imageNum: '17',
    category: 'landscape',
  },
  {
    author: 'Pablo Picasso',
    name: 'Guernica',
    year: '1937',
    imageNum: '18',
    category: 'avant-garde',
  },
  {
    author: 'Paul Gauguin',
    name: 'Where do we come from? What are we? Where are we going?',
    year: '1898',
    imageNum: '19',
    category: 'painting',
  },
  {
    author: 'Bartolome Murillo',
    name: 'Our Lady of the Rosary',
    year: '1655',
    imageNum: '20',
    category: 'renaissance',
  },
  {
    author: 'Pieter Bruegel',
    name: 'Netherlandish Proverbs',
    year: '1559',
    imageNum: '21',
    category: 'renaissance',
  },
  {
    author: 'Jan van Eyck',
    name: 'Arnolfini Portrait',
    year: '1434',
    imageNum: '22',
    category: 'renaissance',
  },
  {
    author: 'Pieter Bruegel',
    name: 'Massacre of the Innocents',
    year: '1567',
    imageNum: '23',
    category: 'renaissance',
  },
  {
    author: 'Konstantin Makovsky',
    name: 'Children running from a thunderstorm',
    year: '1872',
    imageNum: '24',
    category: 'painting',
  },
  {
    author: 'Rembrandt',
    name: 'Danaë',
    year: '1647',
    imageNum: '25',
    category: 'renaissance',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Madonna della seggiola',
    year: '1514',
    imageNum: '26',
    category: 'portrait',
  },
  {
    author: 'Vasily Surikov',
    name: 'The Capture of Snow Town',
    year: '1891',
    imageNum: '27',
    category: 'realism',
  },
  {
    author: 'Ivan Shishkin',
    name: 'Creek in a birch forest',
    year: '1883',
    imageNum: '28',
    category: 'landscape',
  },
  {
    author: 'Vasily Surikov',
    name: 'Conquest of Siberia by Ermak',
    year: '1895',
    imageNum: '29',
    category: 'realism',
  },
  {
    author: 'Vladimir Borovikovsky',
    name: 'Portrait of Maria Lopukhina',
    year: '1797',
    imageNum: '30',
    category: 'portrait',
  },
  {
    author: 'Rene Magritte',
    name: 'The Son of Man',
    year: '1964',
    imageNum: '31',
    category: 'surrealism',
  },
  {
    author: 'Diego Velazquez',
    name: 'Rokeby Venus',
    year: '1651',
    imageNum: '32',
    category: 'painting',
  },
  {
    author: 'Ivan Bogdanov',
    name: 'For the calculation',
    year: '1890',
    imageNum: '33',
    category: 'realism',
  },
  {
    author: 'Rembrandt',
    name: 'The Woman Taken in Adultery',
    year: '1644',
    imageNum: '34',
    category: 'renaissance',
  },
  {
    author: 'John William Waterhouse',
    name: 'The Lady of Shalott',
    year: '1888',
    imageNum: '35',
    category: 'portrait',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'The Great Bathers',
    year: '1887',
    imageNum: '36',
    category: 'painting',
  },
  {
    author: 'Bartolome Murillo',
    name: 'Boy with a Dog',
    year: '1650',
    imageNum: '37',
    category: 'portrait',
  },
  {
    author: 'Vasily Perov',
    name: 'Troika',
    year: '1866',
    imageNum: '38',
    category: 'realism',
  },
  {
    author: 'Nikolay Bogdanov-Belsky',
    name: 'Mental Arithmetic',
    year: '1895',
    imageNum: '39',
    category: 'realism',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Three Tsarevnas of the Underground Kingdom',
    year: '1884',
    imageNum: '40',
    category: 'romanticism',
  },
  {
    author: 'Henri Matisse',
    name: ' La Danse',
    year: '1910',
    imageNum: '41',
    category: 'avant-garde',
  },
  {
    author: 'Edvard Munch',
    name: 'Madonna',
    year: '1894',
    imageNum: '42',
    category: 'expressionism',
  },
  {
    author: 'Marc Chagall',
    name: 'The Promenade',
    year: '1918',
    imageNum: '43',
    category: 'expressionism',
  },
  {
    author: 'Vasily Perov',
    name: 'Procession on Easter',
    year: '1861',
    imageNum: '44',
    category: 'realism',
  },
  {
    author: 'Jheronimus Bosch',
    name: 'The Last Judgment',
    year: '1504',
    imageNum: '45',
    category: 'renaissance',
  },
  {
    author: 'Kirill Lemokh',
    name: 'Varyka',
    year: '1893',
    imageNum: '46',
    category: 'portrait',
  },
  {
    author: 'Jean-Honoré Fragonard',
    name: 'The Stolen Kiss',
    year: '1788',
    imageNum: '47',
    category: 'romanticism',
  },
  {
    author: 'Francois Boucher',
    name: 'Venus Consoling Love',
    year: '1751',
    imageNum: '48',
    category: 'renaissance',
  },
  {
    author: 'Ivan Shishkin',
    name: 'Mast-Tree grove',
    year: '1898',
    imageNum: '49',
    category: 'landscape',
  },
  {
    author: 'Gustav Klimt',
    name: 'Portrait of Adele Bloch-Bauer I',
    year: '1907',
    imageNum: '50',
    category: 'portrait',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Bogatyrs',
    year: '1898',
    imageNum: '51',
    category: 'painting',
  },
  {
    author: 'Wilhelm von Kaulbach',
    name: 'Destruction of Jerusalem',
    year: '1846',
    imageNum: '52',
    category: 'renaissance',
  },
  {
    author: 'Veronese',
    name: 'The Wedding at Cana',
    year: '1562',
    imageNum: '53',
    category: 'renaissance',
  },
  {
    author: 'Andrei Rublev',
    name: 'The Trinity',
    year: '1411',
    imageNum: '54',
    category: 'religion',
  },
  {
    author: 'Vasily Surikov',
    name: 'The Morning of the Streltsy Execution',
    year: '1881',
    imageNum: '55',
    category: 'realism',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Bacchanal of the Andrians',
    year: '1526',
    imageNum: '56',
    category: 'renaissance',
  },
  {
    author: 'Diego Velazquez',
    name: 'Vista del jardín de la Villa Medici en Roma',
    year: '1630',
    imageNum: '57',
    category: 'painting',
  },
  {
    author: 'Edouard Manet',
    name: 'The Luncheon on the Grass',
    year: '1863',
    imageNum: '58',
    category: 'impressionism',
  },
  {
    author: 'Salvador Dali',
    name: 'The Persistence of Memory',
    year: '1931',
    imageNum: '59',
    category: 'avant-garde',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Girls at the Piano',
    year: '1892',
    imageNum: '60',
    category: 'romanticism',
  },
  {
    author: 'Aleksandr Makovsky',
    name: 'I am Bored with You',
    year: '1897',
    imageNum: '61',
    category: 'realism',
  },
  {
    author: 'Diego Velazquez',
    name: 'Las Meninas',
    year: '1656',
    imageNum: '62',
    category: 'renaissance',
  },
  {
    author: 'Antoon van Dyck',
    name: 'Samson and Delilah',
    year: '1628',
    imageNum: '63',
    category: 'renaissance',
  },
  {
    author: 'Pablo Picasso',
    name: 'Girl on a Ball',
    year: '1905',
    imageNum: '64',
    category: 'expressionism',
  },
  {
    author: 'Giovanni Bellini',
    name: 'The Feast of the Gods',
    year: '1514',
    imageNum: '65',
    category: 'renaissance',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'Lady with an Ermine',
    year: '1490',
    imageNum: '66',
    category: 'portrait',
  },
  {
    author: 'Diego Velazquez',
    name: 'Bacchus',
    year: '1628',
    imageNum: '67',
    category: 'renaissance',
  },
  {
    author: 'Bartolome Murillo',
    name: 'The Immaculate Conception of Los Venerables',
    year: '1678',
    imageNum: '68',
    category: 'religion',
  },
  {
    author: 'Theodore Gericault',
    name: 'The Raft of the Medusa',
    year: '1819',
    imageNum: '69',
    category: 'romanticism',
  },
  {
    author: 'Ivan Shishkin',
    name: 'Morning in a Pine Forest',
    year: '1889',
    imageNum: '70',
    category: 'landscape',
  },
  {
    author: 'Jean-Etienne Liotard',
    name: 'The Chocolate Girl',
    year: '1745',
    imageNum: '71',
    category: 'romanticism',
  },
  {
    author: 'Rembrandt',
    name: 'Portrait of Saskia van Uylenburgh',
    year: '1635',
    imageNum: '72',
    category: 'portrait',
  },
  {
    author: 'Ilya Repin',
    name: 'Religious Procession in Kursk Province',
    year: '1883',
    imageNum: '73',
    category: 'realism',
  },
  {
    author: 'Alexey Venetsianov',
    name: 'Sleeping Herd-Boy',
    year: '1826',
    imageNum: '74',
    category: 'portrait',
  },
  {
    author: 'Ivan Bogdanov',
    name: 'Beginner',
    year: '1893',
    imageNum: '75',
    category: 'realism',
  },
  {
    author: 'Henri de Toulouse-Lautrec',
    name: 'A Corner of the Moulin de la Galette',
    year: '1892',
    imageNum: '76',
    category: 'impressionism',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Penitent Magdalene',
    year: '1565',
    imageNum: '77',
    category: 'religion',
  },
  {
    author: 'Diego Velazquez',
    name: 'Infanta margarita',
    year: '1654',
    imageNum: '78',
    category: 'portrait',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Cristo della moneta',
    year: '1516',
    imageNum: '79',
    category: 'religion',
  },
  {
    author: 'Karl Bryullov',
    name: 'Rider',
    year: '1832',
    imageNum: '80',
    category: 'romanticism',
  },
  {
    author: 'Vasily Vereshchagin',
    name: 'The Apotheosis of War',
    year: '1817',
    imageNum: '81',
    category: 'surrealism',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'Annunciation',
    year: '1475',
    imageNum: '82',
    category: 'renaissance',
  },
  {
    author: 'Alexei Savrasov',
    name: 'The Rooks Have Come Back',
    year: '1871',
    imageNum: '83',
    category: 'landscape',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Sacred and Profane Love',
    year: '1516',
    imageNum: '84',
    category: 'renaissance',
  },
  {
    author: 'Jean-Baptiste Greuze',
    name: 'The Village Bride',
    year: '1761',
    imageNum: '85',
    category: 'romanticism',
  },
  {
    author: 'Pablo Picasso',
    name: 'The girls of Avignon',
    year: '1907',
    imageNum: '86',
    category: 'avant-garde',
  },
  {
    author: 'Ilya Repin',
    name: 'Barge Haulers on the Volga',
    year: '1873',
    imageNum: '87',
    category: 'realism',
  },
  {
    author: 'Mikhail Nesterov',
    name: 'The Vision to the Youth Bartholomew',
    year: '1890',
    imageNum: '88',
    category: 'painting',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Madonna del Prato',
    year: '1506',
    imageNum: '89',
    category: 'renaissance',
  },
  {
    author: 'Vasily Tropinin',
    name: 'A girl with a pot of roses',
    year: '1850',
    imageNum: '90',
    category: 'portrait',
  },
  {
    author: 'Caravaggio',
    name: 'The Lute Player',
    year: '1596',
    imageNum: '91',
    category: 'portrait',
  },
  {
    author: 'Vasily Perov',
    name: 'Hunters at rest',
    year: '1871',
    imageNum: '92',
    category: 'painting',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'The Last Supper',
    year: '1498',
    imageNum: '93',
    category: 'religion',
  },
  {
    author: 'Jean-Baptiste Greuze',
    name: 'Young Girl with a Pigeon',
    year: '1765',
    imageNum: '94',
    category: 'painting',
  },
  {
    author: 'William-Adolphe Bouguereau',
    name: 'The Wave',
    year: '1896',
    imageNum: '95',
    category: 'marine',
  },
  {
    author: 'Petrov Vodkin',
    name: 'Bathing of a Red Horse',
    year: '1912',
    imageNum: '96',
    category: 'expressionism',
  },
  {
    author: 'Gustav Klimt',
    name: 'The Kiss',
    year: '1908',
    imageNum: '97',
    category: 'expressionism',
  },
  {
    author: 'Ivan Shishkin',
    name: 'Rye',
    year: '1878',
    imageNum: '98',
    category: 'landscape',
  },
  {
    author: 'Jean-Leon Gerome',
    name: 'Pollice Verso',
    year: '1872',
    imageNum: '99',
    category: 'painting',
  },
  {
    author: 'Vasily Surikov',
    name: 'Boyarina Morozova',
    year: '1887',
    imageNum: '100',
    category: 'painting',
  },
  {
    author: 'Isaac Levitan',
    name: 'Over Eternal Peace',
    year: '1894',
    imageNum: '101',
    category: 'landscape',
  },
  {
    author: 'Thomas Gainsborough',
    name: 'Lady in Blue',
    year: '1780',
    imageNum: '102',
    category: 'portrait',
  },
  {
    author: 'Alexey Venetsianov',
    name: 'Spring, On Ploughed Land',
    year: '1820',
    imageNum: '103',
    category: 'realism',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Salome',
    year: '1515',
    imageNum: '104',
    category: 'religion',
  },
  {
    author: 'Wassily Kandinsky',
    name: 'Composition VIII',
    year: '1923',
    imageNum: '105',
    category: 'avant-garde',
  },
  {
    author: 'Vasily Polenov',
    name: 'In the Park',
    year: '1874',
    imageNum: '106',
    category: 'landscape',
  },
  {
    author: 'Louis-Jean-Francois Lagrenee',
    name: 'Mars and Venus',
    year: '1770',
    imageNum: '107',
    category: 'renaissance',
  },
  {
    author: 'Salvador Dali',
    name: 'Dream Caused by the Flight of a Bee Around a Pomegranate a Second Before Awakening',
    year: '1944',
    imageNum: '108',
    category: 'surrealism',
  },
  {
    author: 'Jan Vermeer',
    name: 'Girl with a Pearl Earring',
    year: '1665',
    imageNum: '109',
    category: 'portrait',
  },
  {
    author: 'Henri Rousseau',
    name: 'The Sleeping Gypsy',
    year: '1897',
    imageNum: '110',
    category: 'surrealism',
  },
  {
    author: 'Vasily Polenov',
    name: 'Crossing of the River Oyat',
    year: '1872',
    imageNum: '111',
    category: 'realism',
  },
  {
    author: 'Edvard Munch',
    name: 'The Scream',
    year: '1893',
    imageNum: '112',
    category: 'expressionism',
  },
  {
    author: 'Karl Bryullov',
    name: 'The Last Day of Pompeii',
    year: '1833',
    imageNum: '113',
    category: 'realism',
  },
  {
    author: 'Ilya Repin',
    name: 'A Summer Landscape',
    year: '1879',
    imageNum: '114',
    category: 'impressionism',
  },
  {
    author: 'Jan Vermeer',
    name: 'The Milkmaid',
    year: '1660',
    imageNum: '115',
    category: 'impressionism',
  },
  {
    author: 'Ivan Aivazovsky',
    name: 'The Ninth Wave',
    year: '1850',
    imageNum: '116',
    category: 'marine',
  },
  {
    author: 'Vincent van Gogh',
    name: 'Sunflowers',
    year: '1888',
    imageNum: '117',
    category: 'expressionism',
  },
  {
    author: 'Valentin Serov',
    name: 'Girl with Peaches',
    year: '1887',
    imageNum: '118',
    category: 'impressionism',
  },
  {
    author: 'Caravaggio',
    name: 'Conversion on the Way to Damascus',
    year: '1601',
    imageNum: '119',
    category: 'painting',
  },
  {
    author: 'Albrecht Durer',
    name: 'Feast of the Rosary',
    year: '1506',
    imageNum: '120',
    category: 'religion',
  },
  {
    author: 'El Greco',
    name: 'The Purification of the Temple',
    year: '1600',
    imageNum: '121',
    category: 'religion',
  },
  {
    author: 'Ilya Repin',
    name: 'Students studying for an exam',
    year: '1864',
    imageNum: '122',
    category: 'painting',
  },
  {
    author: 'Isaac Levitan',
    name: 'March',
    year: '1895',
    imageNum: '123',
    category: 'landscape',
  },
  {
    author: 'William-Adolphe Bouguereau',
    name: 'A Young Girl Defending Herself Against Eros',
    year: '1880',
    imageNum: '124',
    category: 'renaissance',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'Madonna Litta',
    year: '1491',
    imageNum: '125',
    category: 'renaissance',
  },
  {
    author: 'Kazimir Malevich',
    name: 'Black Square',
    year: '1915',
    imageNum: '126',
    category: 'avant-garde',
  },
  {
    author: 'El Greco',
    name: 'Saint Peter and Saint Paul',
    year: '1592',
    imageNum: '127',
    category: 'renaissance',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'A Knight At the Crossroads',
    year: '1878',
    imageNum: '128',
    category: 'romanticism',
  },
  {
    author: 'Konstantin Makovsky',
    name: 'A Boyar Wedding Feast',
    year: '1883',
    imageNum: '129',
    category: 'romanticism',
  },
  {
    author: 'Eugene Delacroix',
    name: 'Liberty Leading the People',
    year: '1830',
    imageNum: '130',
    category: 'romanticism',
  },
  {
    author: 'Vasily Polenov',
    name: "Grandma's Garden",
    year: '1878',
    imageNum: '131',
    category: 'impressionism',
  },
  {
    author: 'Henri Matisse',
    name: 'Family Portrait',
    year: '1911',
    imageNum: '132',
    category: 'expressionism',
  },
  {
    author: 'Konstantin Makovsky',
    name: 'Christmastide Fortune Telling',
    year: '1890',
    imageNum: '133',
    category: 'romanticism',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'The railway bridge in Chatou',
    year: '1875',
    imageNum: '134',
    category: 'marine',
  },
  {
    author: 'Sandro Botticelli',
    name: 'Primavera',
    year: '1482',
    imageNum: '135',
    category: 'renaissance',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'The Umbrellas',
    year: '1886',
    imageNum: '136',
    category: 'impressionism',
  },
  {
    author: 'Gustave Courbet',
    name: "The Artist's Studio",
    year: '1855',
    imageNum: '137',
    category: 'renaissance',
  },
  {
    author: 'Vasily Polenov',
    name: 'Village Mount Okulova',
    year: '1860',
    imageNum: '138',
    category: 'landscape',
  },
  {
    author: 'Konstantin Makovsky',
    name: "Muhammed's carpet moving from Mecca to Cairo",
    year: '1875',
    imageNum: '139',
    category: 'realism',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Bal du moulin de la Galette',
    year: '1876',
    imageNum: '140',
    category: 'impressionism',
  },
  {
    author: 'Ivan Kramskoi',
    name: 'Portrait of an Unknown Woman',
    year: '1883',
    imageNum: '141',
    category: 'portrait',
  },
  {
    author: 'Diego Velazquez',
    name: 'The Forge of Vulcan',
    year: '1630',
    imageNum: '142',
    category: 'renaissance',
  },
  {
    author: 'Ilya Repin',
    name: 'Reply of the Zaporozhian Cossacks to Sultan Mehmed IV',
    year: '1891',
    imageNum: '143',
    category: 'realism',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Young Woman with Unicorn',
    year: '1506',
    imageNum: '144',
    category: 'portrait',
  },
  {
    author: 'Alexander Ivanov',
    name: 'The Appearance of Christ Before the People',
    year: '1857',
    imageNum: '145',
    category: 'renaissance',
  },
  {
    author: 'Edouard Manet',
    name: 'Woman with a Jug',
    year: '1858',
    imageNum: '146',
    category: 'portrait',
  },
  {
    author: 'Tiziano Vecellio',
    name: 'Emperor Karl V',
    year: '1548',
    imageNum: '147',
    category: 'portrait',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Luncheon of the Boating Party',
    year: '1881',
    imageNum: '148',
    category: 'expressionism',
  },
  {
    author: 'Karl Bryullov',
    name: 'Italian Midday',
    year: '1827',
    imageNum: '149',
    category: 'portrait',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Tsar Ivan IV the Terrible',
    year: '1896',
    imageNum: '150',
    category: 'portrait',
  },
  {
    author: 'Pieter Bruegel',
    name: 'The Hunters in the Snow',
    year: '1565',
    imageNum: '151',
    category: 'painting',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Flying Carpet',
    year: '1880',
    imageNum: '152',
    category: 'romanticism',
  },
  {
    author: 'Marc Chagall',
    name: 'I and the Village',
    year: '1911',
    imageNum: '153',
    category: 'surrealism',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'Mona Lisa',
    year: '1505',
    imageNum: '154',
    category: 'portrait',
  },
  {
    author: 'Francesco Bacchiacca',
    name: 'Madonna and Child',
    year: '1520',
    imageNum: '155',
    category: 'renaissance',
  },
  {
    author: 'Jacques-Louis David',
    name: 'Oath of the Horatii',
    year: '1784',
    imageNum: '156',
    category: 'renaissance',
  },
  {
    author: 'Albrecht Durer',
    name: 'Adam and Eve',
    year: '1507',
    imageNum: '157',
    category: 'religion',
  },
  {
    author: 'Bartolome Murillo',
    name: 'Apparition of the Virgin',
    year: '1655',
    imageNum: '158',
    category: 'religion',
  },
  {
    author: 'Vasily Perov',
    name: 'Fowler',
    year: '1870',
    imageNum: '159',
    category: 'painting',
  },
  {
    author: 'Caravaggio',
    name: 'Rest on the Flight into Egypt',
    year: '1596',
    imageNum: '160',
    category: 'renaissance',
  },
  {
    author: 'Francisco Goya',
    name: 'The Third of May',
    year: '1808',
    imageNum: '161',
    category: 'avant-garde',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Galatea',
    year: '1512',
    imageNum: '162',
    category: 'renaissance',
  },
  {
    author: 'Mikhail Vrubel',
    name: 'The Demon Seated',
    year: '1890',
    imageNum: '163',
    category: 'expressionism',
  },
  {
    author: 'Vincent van Gogh',
    name: 'Irises',
    year: '1889',
    imageNum: '164',
    category: 'expressionism',
  },
  {
    author: 'Paul Delaroche',
    name: 'Execution of Lady Jane Grey',
    year: '1833',
    imageNum: '165',
    category: 'romanticism',
  },
  {
    author: 'John Constable',
    name: "Salisbury Cathedral from the Bishop's Grounds",
    year: '1823',
    imageNum: '166',
    category: 'impressionism',
  },
  {
    author: 'Vincent van Gogh',
    name: 'The Starry Night',
    year: '1889',
    imageNum: '167',
    category: 'expressionism',
  },
  {
    author: 'Francois Boucher',
    name: 'Spring anagoria',
    year: '1755',
    imageNum: '168',
    category: 'romanticism',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Madonna of the Rose',
    year: '1518',
    imageNum: '169',
    category: 'religion',
  },
  {
    author: 'Vasily Tropinin',
    name: 'Lace making beauty',
    year: '1823',
    imageNum: '170',
    category: 'portrait',
  },
  {
    author: 'Rembrandt',
    name: "Belshazzar's Feast",
    year: '1635',
    imageNum: '171',
    category: 'portrait',
  },
  {
    author: 'Vasily Surikov',
    name: 'Suvorov Crossing the Alps',
    year: '1899',
    imageNum: '172',
    category: 'realism',
  },
  {
    author: 'Isaac Levitan',
    name: 'Golden Autumn',
    year: '1895',
    imageNum: '173',
    category: 'landscape',
  },
  {
    author: 'Arkhip Kuindzhi',
    name: 'On Valaam Island',
    year: '1873',
    imageNum: '174',
    category: 'landscape',
  },
  {
    author: 'Diego Velazquez',
    name: 'The Surrender of Breda',
    year: '1635',
    imageNum: '175',
    category: 'realism',
  },
  {
    author: 'Ilya Repin',
    name: 'They did not expect him',
    year: '1888',
    imageNum: '176',
    category: 'realism',
  },
  {
    author: 'Francois Boucher',
    name: 'Diana Bathing',
    year: '1742',
    imageNum: '177',
    category: 'renaissance',
  },
  {
    author: 'Albrecht Durer',
    name: 'Feast of the Rosary',
    year: '1506',
    imageNum: '178',
    category: 'religion',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Portrait of Jeanne Samary',
    year: '1877',
    imageNum: '179',
    category: 'portrait',
  },
  {
    author: 'Ilya Repin',
    name: 'Sadko in the Undersea Kingdom',
    year: '1876',
    imageNum: '180',
    category: 'surrealism',
  },
  {
    author: 'Arkhip Kuindzhi',
    name: 'Moonlight Night on the Dnieper',
    year: '1880',
    imageNum: '181',
    category: 'marine',
  },
  {
    author: 'Diego Velazquez',
    name: 'Adoration of the Kings',
    year: '1619',
    imageNum: '182',
    category: 'renaissance',
  },
  {
    author: 'Nikolay Bogdanov-Belsky',
    name: 'At the School Doors',
    year: '1897',
    imageNum: '183',
    category: 'painting',
  },
  {
    author: 'Jheronimus Bosch',
    name: 'The Garden of Earthly Delights',
    year: '1510',
    imageNum: '184',
    category: 'surrealism',
  },
  {
    author: 'Correggio',
    name: 'Danaë',
    year: '1530',
    imageNum: '185',
    category: 'renaissance',
  },
  {
    author: 'Peter Paul Rubens',
    name: 'The Rape of the Daughters of Leucippus',
    year: '1618',
    imageNum: '186',
    category: 'renaissance',
  },
  {
    author: 'Jean Ingres',
    name: 'La Grande Odalisque',
    year: '1814',
    imageNum: '187',
    category: 'portrait',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Sistine Madonna',
    year: '1520',
    imageNum: '188',
    category: 'religion',
  },
  {
    author: 'Rembrandt',
    name: 'The Abduction of Europa',
    year: '1632',
    imageNum: '189',
    category: 'renaissance',
  },
  {
    author: 'Peter Paul Rubens',
    name: 'The Rape of Orithyia by Boreas',
    year: '1615',
    imageNum: '190',
    category: 'renaissance',
  },
  {
    author: 'Arkhip Kuindzhi',
    name: 'Ukrainian Night',
    year: '1876',
    imageNum: '191',
    category: 'landscape',
  },
  {
    author: 'Edgar Degas',
    name: 'Dancers at the Barre',
    year: '1877',
    imageNum: '192',
    category: 'impressionism',
  },
  {
    author: 'Alexey Venetsianov',
    name: 'Summer, Reaping',
    year: '1827',
    imageNum: '193',
    category: 'romanticism',
  },
  {
    author: 'Pierre-Auguste Renoir',
    name: 'Two Sisters',
    year: '1881',
    imageNum: '194',
    category: 'impressionism',
  },
  {
    author: 'Rembrandt',
    name: 'The Night Watch',
    year: '1642',
    imageNum: '195',
    category: 'realism',
  },
  {
    author: 'Edouard Manet',
    name: 'A Bar at the Folies-Bergère',
    year: '1882',
    imageNum: '196',
    category: 'expressionism',
  },
  {
    author: 'Nicolas Poussin',
    name: 'Landscape with Polyphemus',
    year: '1649',
    imageNum: '197',
    category: 'landscape',
  },
  {
    author: 'Pieter Bruegel',
    name: 'The Blind Leading the Blind',
    year: '1568',
    imageNum: '198',
    category: 'renaissance',
  },
  {
    author: 'Viktor Vasnetsov',
    name: 'Ivan Tsarevich Riding the Grey Wolf',
    year: '1888',
    imageNum: '199',
    category: 'painting',
  },
  {
    author: 'Sandro Botticelli',
    name: 'The Birth of Venus',
    year: '1486',
    imageNum: '200',
    category: 'renaissance',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'Virgin of the Rocks',
    year: '1486',
    imageNum: '201',
    category: 'religion',
  },
  {
    author: 'Akseli Gallen-Kallela',
    name: 'The Lovers',
    year: '1916',
    imageNum: '202',
    category: 'avant-garde',
  },
  {
    author: 'Vincent van Gogh',
    name: 'Self-portrait with Bandaged Ear',
    year: '1889',
    imageNum: '203',
    category: 'expressionism',
  },
  {
    author: 'Claude Monet',
    name: 'Impression, Sunrise',
    year: '1882',
    imageNum: '204',
    category: 'marine',
  },
  {
    author: 'Rembrandt',
    name: 'The Return of the Prodigal Son',
    year: '1662',
    imageNum: '205',
    category: 'painting',
  },
  {
    author: 'Caravaggio',
    name: 'Young Sick Bacchus',
    year: '1593',
    imageNum: '206',
    category: 'portrait',
  },
  {
    author: 'Ivan Aivazovsky',
    name: 'Moon Path',
    year: '1886',
    imageNum: '207',
    category: 'marine',
  },
  {
    author: 'Vincent van Gogh',
    name: 'Wheat Field with Cypresses',
    year: '1889',
    imageNum: '208',
    category: 'expressionism',
  },
  {
    author: 'Akseli Gallen-Kallela',
    name: 'Boy and a Crow',
    year: '1884',
    imageNum: '209',
    category: 'painting',
  },
  {
    author: 'Jan Vermeer',
    name: 'The Astronomer',
    year: '1668',
    imageNum: '210',
    category: 'renaissance',
  },
  {
    author: 'Peter Paul Rubens',
    name: 'The Union of Earth and Water',
    year: '1618',
    imageNum: '211',
    category: 'renaissance',
  },
  {
    author: 'Claude Monet',
    name: 'Haystacks',
    year: '1886',
    imageNum: '212',
    category: 'landscape',
  },
  {
    author: 'Jean-Honoré Fragonard',
    name: 'The Bolt',
    year: '1777',
    imageNum: '213',
    category: 'renaissance',
  },
  {
    author: 'Edouard Manet',
    name: 'A Bar at the Folies-Bergere',
    year: '1882',
    imageNum: '214',
    category: 'avant-garde',
  },
  {
    author: 'Vincent van Gogh',
    name: 'The Night Cafe',
    year: '1888',
    imageNum: '215',
    category: 'expressionism',
  },
  {
    author: 'Claude Monet',
    name: 'The Waterlily Pond',
    year: '1899',
    imageNum: '216',
    category: 'expressionism',
  },
  {
    author: 'Ivan Aivazovsky',
    name: 'The Tempest',
    year: '1868',
    imageNum: '217',
    category: 'marine',
  },
  {
    author: 'Jan Vermeer',
    name: 'The Lacemaker',
    year: '1671',
    imageNum: '218',
    category: 'portrait',
  },
  {
    author: 'Karl Bryullov',
    name: 'Self-portrait',
    year: '1848',
    imageNum: '219',
    category: 'portrait',
  },
  {
    author: 'Pieter Bruegel',
    name: 'The Tower of Babel',
    year: '1563',
    imageNum: '220',
    category: 'surrealism',
  },
  {
    author: 'Paul Gauguin',
    name: 'Interior of a Restaurant in Arles',
    year: '1888',
    imageNum: '221',
    category: 'avant-garde',
  },
  {
    author: 'Ivan Shishkin',
    name: 'Pine forest',
    year: '1895',
    imageNum: '222',
    category: 'landscape',
  },
  {
    author: 'Claude Monet',
    name: 'The Luncheon on the Grass',
    year: '1865',
    imageNum: '223',
    category: 'impressionism',
  },
  {
    author: 'Raffaello Sanzio',
    name: 'Saint George and the Dragon',
    year: '1506',
    imageNum: '224',
    category: 'renaissance',
  },
  {
    author: 'Pablo Picasso',
    name: 'Absinthe Drinker',
    year: '1901',
    imageNum: '225',
    category: 'surrealism',
  },
  {
    author: 'Edgar Degas',
    name: 'Before the Performance',
    year: '1880',
    imageNum: '226',
    category: 'expressionism',
  },
  {
    author: 'Nicholas Roerich',
    name: 'Remember',
    year: '1924',
    imageNum: '227',
    category: 'surrealism',
  },
  {
    author: 'Ilya Repin',
    name: 'Dragonfly',
    year: '1884',
    imageNum: '228',
    category: 'romanticism',
  },
  {
    author: 'Claude Monet',
    name: 'Waterloo Bridge, Sun Through Fog',
    year: '1903',
    imageNum: '229',
    category: 'impressionism',
  },
  {
    author: 'Isaac Levitan',
    name: 'Spring, High Water',
    year: '1897',
    imageNum: '230',
    category: 'landscape',
  },
  {
    author: 'Akseli Gallen-Kallela',
    name: 'The First Lesson',
    year: '1889',
    imageNum: '231',
    category: 'realism',
  },
  {
    author: 'Ivan Aivazovsky',
    name: 'Tempest on the sea',
    year: '1873',
    imageNum: '232',
    category: 'marine',
  },
  {
    author: 'Edgar Degas',
    name: 'The Dance Class',
    year: '1874',
    imageNum: '233',
    category: 'expressionism',
  },
  {
    author: 'Nicholas Roerich',
    name: 'Mountain landscape',
    year: '1933',
    imageNum: '234',
    category: 'impressionism',
  },
  {
    author: 'Leonardo da Vinci',
    name: 'The Virgin and Child with Saint Anne',
    year: '1510',
    imageNum: '235',
    category: 'religion',
  },
  {
    author: 'El Greco',
    name: 'A boy blowing on an ember to light a candle',
    year: '1572',
    imageNum: '236',
    category: 'painting',
  },
  {
    author: 'Pablo Picasso',
    name: 'Friendship',
    year: '1908',
    imageNum: '237',
    category: 'avant-garde',
  },
  {
    author: 'Akseli Gallen-Kallela',
    name: 'A Girl Standing in the Windу',
    year: '1893',
    imageNum: '238',
    category: 'romanticism',
  },
  {
    author: 'Ivan Aivazovsky',
    name: 'Wave',
    year: '1889',
    imageNum: '239',
    category: 'marine',
  },
];
