import "./style.scss"

import images from "./images"
import { shuffle } from "./js/questionsAuthors"
import { Question } from "./js/questionsAuthors"
import { QuestionPictures } from "./js/questionsPictures"
import { Category } from "./js/category"
import { categoriesWrapper } from "./js/categoriesPage"
import { createCategories } from "./js/categoriesPage"
import { pageCategories } from "./js/categoriesPage"
import { showCategoriesPage } from "./js/categoriesPage"
import { hideCategoriesPage } from "./js/categoriesPage"
import { pageStarting } from "./js/settingsPage"
import { initPicturesQuestions } from "./js/categoriesPage"
import { showStartingPage } from "./js/startingPage"
import { hideStartingPage } from "./js/startingPage"
import { timer } from "./js/timerFunction"
import { hideQuestionAuthorPage} from "./js/questionsAuthorsPage"
import { showQuestionAuthorPage } from "./js/questionsAuthorsPage"
import { category } from "./js/categoriesPage"
import { createQuestionsAuthorPage } from "./js/questionsAuthorsPage"
import { questionsAuthorPage } from "./js/questionsAuthorsPage"


import "./js/questionsAuthors"
import "./js/questionsPictures"
import "./js/category"
import "./js/settingsPage"
import "./js/startingPage"
import "./js/categoriesPage"
import "./js/timerFunction"
import "./js/questionsAuthorsPage"



